version: "3.7"
services:
  web:
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ../:/app
      - ./web/site.conf:/etc/nginx/conf.d/default.conf
      - web-storage:/app/storage
    depends_on:
      - db
      - php
    links:
      - php
  php:
    build:
      context: ..
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ../:/app
  db:
    build:
      context: ..
      dockerfile: ./docker/db/Dockerfile
    restart: unless-stopped
    volumes:
      - ./db/db.conf:/etc/mysql/conf.d/local.snf
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: usr
      MYSQL_PASSWORD: example
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON

volumes:
  web-storage:
